export enum ICON_NAMES {
  archive = 'archive',
  camera = 'camera',
  checkCircle = 'check-circle',
  clock = 'clock',
  exclamationCircle = 'exclamation-circle',
  exclamation = 'exclamation',
  facebook = 'facebook',
  google = 'google',
  heart = 'heart',
  informationCircle = 'information-circle',
  linkedin = 'linkedin',
  logout = 'logout',
  moneyBag = 'money-bag',
  pencil = 'pencil',
  plus = 'plus',
  qrCode = 'qr-code',
  search = 'search',
  settings = 'settings',
  store = 'store',
  twitter = 'twitter',
  user = 'user',
}
